<?php

/**
 * @file
 * Contains az_article.module.
 */

use Drupal\comment\Entity\Comment;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\Component\Utility\Random;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function az_article_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return;
}

function _az_article_add_article_to_media($media, $articleId) {
  $articles = $media->get('field_articles');
  $found = false;
  if (!empty($articles)) {
    $values = $articles->getValue();
    foreach ($values as $value) {
      if ($value['target_id'] == $articleId) {
        $found = TRUE;
      }
    }
  }
  if (!$found) {
    $media->field_articles->appendItem($articleId);
    $media->save();
  }
}

/**
 * Implements hook_node_presave().
 *
 * Storing a node - assign
 */
function az_article_node_presave(Node $node) {
  if ($node->getType() == 'article') {

    // Add article reference to media entities on that page.
    $articleId = $node->id();
    $mediaRef = $node->get('field_media');
    if ($mediaRef) {
      $value = $mediaRef->getValue();
      if (!empty($value[0])) {
        $mediaId = $value[0]['target_id'];
        $media = \Drupal::entityManager()->getStorage('media')->load($mediaId);
        _az_article_add_article_to_media($media, $articleId);
      }
    }

    $bodyRef = $node->get('field_body');
    $bodyValue = $bodyRef->getValue();
    if (!empty($bodyValue[0])) {
      preg_match_all("/data-entity-uuid=\".*?\"/", $bodyValue[0]['value'], $matches);
      foreach($matches[0] as $match) {
        $uuid = explode('"', $match)[1];
        $media = \Drupal::entityManager()->loadEntityByUuid('media', $uuid);
        _az_article_add_article_to_media($media, $articleId);
      }
    }
  }
  return;
}
/**
 * Implements HOOK_entity_presave().
 *
 */
function az_article_entity_presave(EntityInterface $entity) {
  return;
}

function az_article_comment_presave(Comment $comment) {
  $articleId = $comment->get('entity_id')->getValue()[0]['target_id'];
  $bodyRef = $comment->get('comment_body');
  $bodyValue = $bodyRef->getValue();
  if (!empty($bodyValue[0])) {
    preg_match_all("/data-entity-uuid=\".*?\"/", $bodyValue[0]['value'], $matches);
    foreach($matches[0] as $match) {
      $uuid = explode('"', $match)[1];
      $media = \Drupal::entityManager()->loadEntityByUuid('media', $uuid);
      _az_article_add_article_to_media($media, $articleId);
    }
  }
  return;
}

function az_article_media_presave(EntityInterface $entity) {
  return;
}

function az_article_file_presave(EntityInterface $entity) {
  return;
}

function az_article_group_content_alter($group_content_entity, $entity) {
// Get the Group ID
// Get the Article ID
// Get the Media
//   for each media item
//     Add the article to the media
//     Add group to the media
//     Add topics - or should that come from the article
//$gid = $group_content_entity->gid->value;
//$media = $entity->get('field_media');
//return;
}
