# Schema for the configuration files of the G2 module.

g2.settings:
  type: config_object
  label: 'G2 configuration'
  mapping:
    block:
      label: 'Blocks'
      type: mapping
      mapping:
        alphabar:
          label: 'Alphabar'
          type: mapping
          mapping:
            row_length:
              type: integer
              label: 'Row length of the themed alphabar, in number of runes'
        latest:
          label: 'Latest updated entries'
          type: mapping
          mapping:
            count:
              type: integer
              label: 'Number of entries in latest(n) lists'
        random:
          label: 'Random entry'
          type: mapping
          mapping:
            show_terms:
              type: boolean
              label: 'Show terms on random node'
            store:
              type: boolean
              label: 'Store the last random value. True is better for smaller sites, false is better for larger sites.'
        top:
          label: 'Most viewed entries'
          type: mapping
          mapping:
            count:
              type: integer
              label: 'Number of entries in top(n) lists'
        wotd:
          label: 'Word of the day'
          type: mapping
          mapping:
            auto_change:
              type: boolean
              label: 'Automatically change the WOTD every day ?'
            body_size:
              type: integer
              label: 'Size of body summary included in WOTD block.'
            links:
              type: mapping
              label: 'Links included in the WOTD block'
              mapping:
                feed:
                  type: boolean
                  label: 'Link to the WOTD feed'
                node:
                  type: boolean
                  label: 'Link to the WOTD node'
                terms:
                  type: boolean
                  label: 'Link to the term feeds, if show_terms is true. Ignored otherwise.'
            show_terms:
              type: boolean
              label: 'Show terms on WOTD node'
    service:
      type: mapping
      label: 'Services'
      mapping:
        alphabar:
          type: mapping
          label: 'Alphabar'
          mapping:
            contents:
              type: string
              label: 'Initials used in the Alphabar'
        latest:
          type: mapping
          label: 'Latest updated entries'
          mapping:
            max_count:
              type: integer
              label: 'Maximum number of entries in latest(n) list.'
        top:
          type: mapping
          label: 'Most viewed entries'
          mapping:
            max_count:
              type: integer
              label: 'Maximum number of entries in top(n) list.'

    controller:
      type: mapping
      label: 'Controllers and routing'
      mapping:
        main:
          type: mapping
          label: 'Main page'
          mapping:
            nid:
              type: integer
              label: 'Nid of the unpublished node used as main page for G2'
            route:
              type: string
              label: 'The route to use for the G2 main page. Allows replacement by a custom route.'
        entries:
          type: mapping
          label: 'Entries-by-name page'
          mapping:
            route:
              type: string
              label: 'The route to use for the entries disambiguation page. Allows replacement by a custom route.'
        initial:
          type: mapping
          label: 'Entries-by-initial-segment page'
          mapping:
            route:
              type: string
              label: 'The route to use for the entries-by-initial page. Allows easy replacement of the node-based default mechanism.'
        adder:
          type: mapping
          label: 'Node add page'
          mapping:
            route:
              type: string
              label: 'The route for the default G2 node add page. Allows replacement by a custom route.'
        homonyms:
          type: mapping
          label: 'Homonyms disambiguation page'
          mapping:
            redirect_on_single_match:
              type: boolean
              label: 'Jump to single match on homonyms/entries pages ?'
            nid:
              type: integer
              label: 'The nid for the homonyms disambiguation page. Deprecated: use a view instead.'
            redirect_status:
              type: integer
              label: 'Default HTTP status code for automatic redirection.'
            route:
              type: string
              label: 'The route to the disambiguation page for homonyms. This allows overriding the default node-based mechanism.'
            vid:
              type: string
              label: 'The default view for the homonyms disambiguation page. Select among views tagged as G2 or set to empty for a plain node list in g2_entry_list mode.'
        wotd:
          type: mapping
          label: 'WOTD RSS feed'
          mapping:
            title:
              type: string
              label: 'The feed title.'
            description:
              type: string
              label: 'The feed description. !site is a link to the G2 main page on the site.'
            feed_author:
              type: boolean
              label: Include the author in the feed entries

    rpc:
      type: mapping
      label: API
      mapping:
        client:
          type: mapping
          label: 'API Client'
          mapping:
            remote:
              type: string
              label: 'The URL of the remote reference glossary.'
        server:
          type: mapping
          label: 'API Server'
          mapping:
            enabled:
              type: boolean
              label: 'Is the XML-RPC API enabled ?'
            throttle:
              type: float
              label: 'Coefficient limit for API operations over block settings. Max: 1.0.'
        # TODO check whether this is one is not actually a constant.
        local:
          type: string
          label: 'Non-remote path'

    formatting:
      type: mapping
      label: 'Content formatting'
      mapping:
        hidden_extra_title:
          type: boolean
          label: 'Add a "hidden extra title" on G2 entry node views.'
        hide_free_tagging:
          type: boolean
          label: 'Hide information from tag vocabularies to non-G2 admins.'
        tooltips_level:
          type: integer
          label: 'Tooltips on definitions ? 0: no, 1: title, 2: teasers.'
        title:
          type: string
          label: 'Override for default site title on G2 entry node pages. Translatable: @title is the node original title.'
